force-app/main/default/objects/Propulsion__c/Propulsion__c.object-meta.xml
<CustomObject>
    <label>Propulsion</label>
    <nameField>
        <label>Propulsion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propulsions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Propulsion__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Propulsions</relationshipLabel>
    <relationshipName>Propulsions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Propulsion_Part__c/Propulsion_Part__c.object-meta.xml
<CustomObject>
    <label>Propulsion Part</label>
    <nameField>
        <label>Propulsion Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propulsion Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Propulsion_Part__c/fields/Propulsion__c.field-meta.xml
<CustomField>
    <fullName>Propulsion__c</fullName>
    <label>Propulsion</label>
    <referenceTo>Propulsion__c</referenceTo>
    <relationshipLabel>Propulsion Parts</relationshipLabel>
    <relationshipName>Propulsion_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Propulsion_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT SENT</fullName>
                <default>true</default>
                <label>NOT SENT</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>ARRIVED</fullName>
            </value>
            <value>
                <fullName>ACCEPTED/WARRANTY</fullName>
            </value>
            <value>
                <fullName>END OF WARRANTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Truck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trucks</relationshipLabel>
    <relationshipName>Trucks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck_Part__c/Truck_Part__c.object-meta.xml
<CustomObject>
    <label>Truck Part</label>
    <nameField>
        <label>Truck Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Truck Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOT SENT</fullName>
                <default>true</default>
                <label>NOT SENT</label>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
            <value>
                <fullName>ARRIVED</fullName>
            </value>
            <value>
                <fullName>ACCEPTED/WARRANTY</fullName>
            </value>
            <value>
                <fullName>END OF WARRANTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ObjectStatusUpdate/ObjectStatusUpdateTest.cls
/******************************************************************************
* Author: Vladimir Bessonov
* Date: Sep 10, 2020
* Descpription: Test Class for ObjectStatusUpdate - after each part of component is udpated to new status, 
status of component is changed

*/

@isTest(SeeAllData=true)
public with sharing class ObjectStatusUpdateTest {
  @isTest
  static void updateStatusSent() {
    Date TodayDate = Date.today();
    Truck__c Comp = new Truck__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Truck_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Truck_Part__c
      WHERE Truck__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Truck_Part__c part : Parts) {
      part.Status__c = 'SENT';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'SENT';

    Truck__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Truck__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated); // ?
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusArrived() {
    Date TodayDate = Date.today();
    Truck__c Comp = new Truck__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Truck_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Truck_Part__c
      WHERE Truck__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Truck_Part__c part : Parts) {
      part.Status__c = 'ARRIVED';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'ARRIVED';

    Truck__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Truck__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated); // ?
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusAccepted() {
    Date TodayDate = Date.today();
    Truck__c Comp = new Truck__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Truck_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Truck_Part__c
      WHERE Truck__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Truck_Part__c part : Parts) {
      part.Status__c = 'ACCEPTED/WARRANTY';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'ACCEPTED/WARRANTY';

    Truck__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Truck__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + CompUpdated);
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusEndOfWarranty() {
    Date TodayDate = Date.today();
    Truck__c Comp = new Truck__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Truck_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Truck_Part__c
      WHERE Truck__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Truck_Part__c part : Parts) {
      part.Status__c = 'END OF WARRANTY';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'END OF WARRANTY';

    Truck__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Truck__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated);
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusPropSent() {
    Date TodayDate = Date.today();
    Propulsion__c Comp = new Propulsion__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Propulsion_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Propulsion_Part__c
      WHERE Propulsion__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Propulsion_Part__c part : Parts) {
      part.Status__c = 'SENT';
    }
    System.debug('UPDATE PARTS');
    update Parts;

    String ExpectedStatus = 'SENT';

    Propulsion__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Propulsion__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated); // ?
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusPropArrived() {
    Date TodayDate = Date.today();
    Propulsion__c Comp = new Propulsion__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Propulsion_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Propulsion_Part__c
      WHERE Propulsion__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Propulsion_Part__c part : Parts) {
      part.Status__c = 'ARRIVED';
    }
    System.debug('UPDATE PARTS');
    update Parts;

    String ExpectedStatus = 'ARRIVED';

    Propulsion__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Propulsion__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated);
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusPropAccepted() {
    Date TodayDate = Date.today();
    Propulsion__c Comp = new Propulsion__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Propulsion_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Propulsion_Part__c
      WHERE Propulsion__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Propulsion_Part__c part : Parts) {
      part.Status__c = 'ACCEPTED/WARRANTY';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'ACCEPTED/WARRANTY';

    Propulsion__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Propulsion__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated);
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }

  @isTest
  static void updateStatusPropEndOfWarranty() {
    Date TodayDate = Date.today();
    Propulsion__c Comp = new Propulsion__c(
      Name = 'testset',
      Project__c = 'a3E030000008cFzEAI',
      Status__c = 'NOT SENT'
    );

    insert Comp;

    List<Propulsion_Part__c> Parts = [
      SELECT ID, Status__c, Name
      FROM Propulsion_Part__c
      WHERE Propulsion__c = :Comp.id FOR UPDATE
    ];
    System.debug('Comp: ' + Comp);
    System.debug('Parts ' + Parts);
    for (Propulsion_Part__c part : Parts) {
      part.Status__c = 'END OF WARRANTY';
    }
    System.debug('UPDATE PARTS');
    update Parts;
    String ExpectedStatus = 'END OF WARRANTY';

    Propulsion__c CompUpdated = [
      SELECT ID, Status__c, Name
      FROM Propulsion__c
      WHERE ID = :Comp.id FOR UPDATE
    ];
    System.debug(CompUpdated.Status__c);
    System.debug('Comp: ' + CompUpdated); // ?
    System.assertEquals(ExpectedStatus, CompUpdated.Status__c);
  }
}