force-app/main/default/objects/Commissioning_Equipment__c/Commissioning_Equipment__c.object-meta.xml
<CustomObject>
    <label>Commissioning tool</label>
    <nameField>
        <label>Commissioning Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissioning tools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Calibration_Valid__c.field-meta.xml
<CustomField>
    <fullName>Calibration_Valid__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date when Calibration expires</description>
    <label>Calibration Valid</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Name</field>
            <operation>equals</operation>
            <valueField>Project__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Commissioning tools</relationshipLabel>
    <relationshipName>Commissioning_tools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOT CALIBRATED</fullName>
                <default>true</default>
                <label>NOT CALIBRATED</label>
            </value>
            <value>
                <fullName>&lt; 3 Months to expire</fullName>
            </value>
            <value>
                <fullName>CALIBRATED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommissioningTools/CommissioningTool.cls
/******************************************************************************
* Author: Vladimir Bessonov
* Date: Aug 30, 2020
* Descpription: Update Commissioning Tool status when Calibration_Valid__c is changed

*/
public without sharing class CommissioningTool {
  public CommissioningTool() {
  }

  public static void updateCommissioningToolStatus(ID toolID) {
    List<Commissioning_Equipment__c> ToolList = [
      SELECT ID, Name, Calibration_Valid__c, Status__c
      FROM Commissioning_Equipment__c
      WHERE ID = :toolID
      LIMIT 1
    ]; //
    System.debug(ToolList);
    string State = 'NOT CALIBRATED';
    Date Calibration = ToolList[0].Calibration_Valid__c;
    Date today = System.today();

    if (today <= Calibration && today.daysBetween(Calibration) > 90) {
      State = 'CALIBRATED';
    }

    if (today <= Calibration && today.daysBetween(Calibration) < 90) {
      State = '< 3 months to expire';
    }
    ToolList[0].Status__c = State;
    update ToolList;
  }

  public static void updateCommissioningToolStatus() {
    List<Commissioning_Equipment__c> ToolList = [
      SELECT
        ID,
        Name,
        Calibration_Valid__c,
        Status__c,
        Serial_Number__c,
        Project__c,
        CreatedById
      FROM Commissioning_Equipment__c
    ]; //
    Date today = System.today();

    List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
    List<ID> ownerids = new List<ID>();
    List<String> sendTo = new List<String>();
    List<User> users = new List<User>();

    for (Commissioning_Equipment__c tool : ToolList) {
      string State = 'NOT CALIBRATED';
      Date Calibration = tool.Calibration_Valid__c;
      if (today <= Calibration && today.daysBetween(Calibration) > 90) {
        State = 'CALIBRATED';
      }

      if (today <= Calibration && today.daysBetween(Calibration) < 90) {
        State = '< 3 months to expire';
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        string body =
          'The tool will be out of calibration soon: ' +
          tool.Name +
          ' - ' +
          tool.Serial_Number__c +
          ' </b> Project <p>' +
          +tool.Project__c +
          '<a> Best Regards </a>';
        mail.setHtmlBody(body);
        mail.setSubject(
          'Calibration needed:' +
          tool.Name +
          ' - ' +
          tool.Serial_Number__c
        );
        ownerids.add(tool.CreatedById);
        mail.setTargetObjectId(tool.CreatedById);
        mail.setSaveAsActivity(false);
        mails.add(mail);
      }
      tool.Status__c = State;
    }

    if (ownerids.size() > 0) {
      Messaging.sendEmail(mails);
    }
    update ToolList;
  }
}