force-app/main/default/objects/Commissioning_Equipment__c/Commissioning_Equipment__c.object-meta.xml
<CustomObject>
    <label>Commissioning tool</label>
    <nameField>
        <label>Commissioning Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissioning tools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Calibration_Valid__c.field-meta.xml
<CustomField>
    <fullName>Calibration_Valid__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date when Calibration expires</description>
    <label>Calibration Valid</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Name</field>
            <operation>equals</operation>
            <valueField>Project__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Commissioning tools</relationshipLabel>
    <relationshipName>Commissioning_tools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commissioning_Equipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOT CALIBRATED</fullName>
                <default>true</default>
                <label>NOT CALIBRATED</label>
            </value>
            <value>
                <fullName>&lt; 3 Months to expire</fullName>
            </value>
            <value>
                <fullName>CALIBRATED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommissioningTools/CommissioningToolTest.cls
/******************************************************************************
* Author: Vladimir Bessonov
* Date: Aug 30, 2020
* Descpription: Test Class for CommissioningTool

*/
@isTest
public class CommissioningToolTest {
  @isTest
  static void updateToolStatus() {
    Date TodayDate = Date.today();
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    insert Tool;
    CommissioningTool.updateCommissioningToolStatus(Tool.ID);
    Commissioning_Equipment__c NewTool = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTool);
    String Expected = '< 3 Months to expire';
    String Actual = (String) NewTool.Status__c;
    System.debug(Actual);
    System.assertEquals(Expected, Actual);
  }

  @isTest
  static void updateToolStatusCalibrated() {
    Date TodayDate = Date.today().addMonths(4);
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    insert Tool;
    CommissioningTool.updateCommissioningToolStatus(Tool.ID);
    Commissioning_Equipment__c NewTool = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTool);
    String Expected = 'CALIBRATED';
    String Actual = (String) NewTool.Status__c;
    System.debug(Actual);
    System.assertEquals(Expected, Actual);
  }

  @isTest
  static void updateToolStatusNotCalibrated() {
    Date TodayDate = Date.today().addMonths(-1);
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    insert Tool;
    CommissioningTool.updateCommissioningToolStatus(Tool.ID);
    Commissioning_Equipment__c NewTool = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTool);
    String Expected = 'NOT CALIBRATED';
    String Actual = (String) NewTool.Status__c;
    System.debug(Actual);
    System.assertEquals(Expected, Actual);
  }

  @isTest
  static void updateToolsStatus() {
    Date TodayDate = Date.today();
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    Commissioning_Equipment__c Tool1 = new Commissioning_Equipment__c(
      Name = 'TEST1',
      Type__c = 'TEST1',
      Serial_Number__c = '12345679',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );

    insert Tool;
    insert Tool1;
    CommissioningTool.updateCommissioningToolStatus();
    List<Commissioning_Equipment__c> NewTools = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTools);
    Boolean Passed = true;
    String Expected = '< 3 Months to expire';
    for (Commissioning_Equipment__c eq : NewTools) {
      String Actual = (String) eq.Status__c;
      if (Expected != Actual) {
        Passed = false;
      }
    }
    System.assertEquals(Passed, true);
  }

  @isTest
  static void updateToolsStatusCalibrated() {
    Date TodayDate = Date.today().addMonths(4);
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    Commissioning_Equipment__c Tool1 = new Commissioning_Equipment__c(
      Name = 'TEST1',
      Type__c = 'TEST1',
      Serial_Number__c = '12345679',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );

    insert Tool;
    insert Tool1;
    CommissioningTool.updateCommissioningToolStatus();
    List<Commissioning_Equipment__c> NewTools = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTools);
    Boolean Passed = true;
    String Expected = 'CALIBRATED';
    for (Commissioning_Equipment__c eq : NewTools) {
      String Actual = (String) eq.Status__c;
      if (Expected != Actual) {
        Passed = false;
      }
    }
    System.assertEquals(Passed, true);
  }

  @isTest
  static void updateToolsStatusNotCalibrated() {
    Date TodayDate = Date.today().addMonths(-1);
    Commissioning_Equipment__c Tool = new Commissioning_Equipment__c(
      Name = 'TEST',
      Type__c = 'TEST',
      Serial_Number__c = '12345678',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );
    Commissioning_Equipment__c Tool1 = new Commissioning_Equipment__c(
      Name = 'TEST1',
      Type__c = 'TEST1',
      Serial_Number__c = '12345679',
      Project__c = 'a3E030000008cFzEAI',
      Calibration_Valid__c = TodayDate
    );

    insert Tool;
    insert Tool1;
    CommissioningTool.updateCommissioningToolStatus();
    List<Commissioning_Equipment__c> NewTools = [
      SELECT Id, Status__c
      FROM Commissioning_Equipment__c
    ];
    System.debug(NewTools);
    Boolean Passed = true;
    String Expected = 'NOT CALIBRATED';
    for (Commissioning_Equipment__c eq : NewTools) {
      String Actual = (String) eq.Status__c;
      if (Expected != Actual) {
        Passed = false;
      }
    }
    System.assertEquals(Passed, true);
  }
}